name: "Spice Labs Survey"
description: "Runs The Spice Labs Surveyor to survey files and upload results."

inputs:
  file_path:
    description: "Path to local files to survey"
    required: false
    default: "."
  spice_pass:
    description: "Spice Pass token"
    required: true
  tag:
    description: "Tag to associate with the survey"
    required: true
  cli_image:
    description: "Docker image for the CLI"
    required: false
    default: "spicelabs/spice-labs-cli:latest"

runs:
  using: "composite"
  steps:
    - name: Run Spice Labs Surveyor
      shell: bash
      run: |
        set -euo pipefail

        echo "Starting The Spice Labs Surveyor"

        docker run \
          -v "${{ inputs.file_path }}:/mnt/input:ro" \
          -e SPICE_PASS="${{ inputs.spice_pass }}" \
          "${{ inputs.cli_image }}" \
          --log-level all \
          --input /mnt/input \
          --tag "${{ inputs.tag }}"

        echo "Survey and Upload complete"
