name: Spice Labs, Inc. Scan & Upload

description: Runs The Spice Labs CLI scan, then uploads results.

inputs:
  file_path:
    description: Path to local files to scan
    required: false
    default: .
  spice_pass:
    description: Spice Pass
    required: true
  tag:
    description: Tag for the scan
    required: true

runs:
  using: "composite"
  steps:
    - name: Build ADG
      shell: bash
      run: |
        echo "🔍 Running The Spice Labs CLI Scan & Upload..."

        docker run \
          -v "${{ inputs.file_path }}:/mnt/input:ro" \
          -e SPICE_PASS="${{ secrets.SPICE_PASS }}" \
          spicelabs/spice-labs-cli:0.2 \
          --log-level=all \
          --input=/mnt/input \
          --tag="${{ inputs.tag }}"

        echo "✅ ADG creation & upload complete"
