name: Spice Labs, Inc. Scan & Upload

description: Runs The Spice Labs CLI scan, then uploads results.

inputs:
  file_path:
    description: Path to local files to scan
    required: false
    default: .
  spice_pass:
    description: Spice Pass
    required: true
  tag:
    description: Tag for the scan
    required: true
  cli_image:
    description: Docker image for the CLI
    required: false
    default: spicelabs/spice-labs-cli:latest

runs:
  using: "composite"
  steps:
    - name: Run Spice Labs CLI Scan & Upload
      shell: bash
      run: |
        set -euo pipefail

        echo "🔍 Running The Spice Labs CLI Scan & Upload..."

        docker run \
          -v "${{ inputs.file_path }}:/mnt/input:ro" \
          -e SPICE_PASS="${{ inputs.spice_pass }}" \
          "${{ inputs.cli_image }}" \
          --log-level all \
          --input /mnt/input \
          --tag "${{ inputs.tag }}"

        echo "✅ ADG creation & upload complete"
